# Generated by Django 5.2.8 on 2025-12-15 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0017_alter_sitetheme_theme_type_staffbroadcast_and_more'),
        ('estateApp', '0095_estate_estate_size_unit_alter_estate_estate_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_departments', to='estateApp.company')),
            ],
            options={
                'verbose_name': 'Staff Department',
                'verbose_name_plural': 'Staff Departments',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role/Position name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='adminSupport.staffdepartment')),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
