# Generated by Django 5.2.8 on 2025-12-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0018_staffdepartment_staffrole'),
        ('estateApp', '0095_estate_estate_size_unit_alter_estate_estate_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='estateApp.company'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='adminSupport.staffdepartment'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='adminSupport.staffrole'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(blank=True, help_text='Role/Position (legacy field)', max_length=120),
        ),
    ]
