# Generated by Django 5.2.8 on 2025-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0019_staffmember_company_staffmember_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Staff profile picture/passport', null=True, upload_to='staff_profiles/'),
        ),
    ]
