# Generated by Django 5.2.8 on 2025-12-15 17:10

import adminSupport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0020_staffmember_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Staff profile picture/passport', null=True, upload_to=adminSupport.models.staff_profile_picture_path),
        ),
    ]
