# Generated by Django 5.2.8 on 2025-12-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0021_alter_staffmember_profile_picture'),
        ('estateApp', '0095_estate_estate_size_unit_alter_estate_estate_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this log entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='estateApp.company'),
        ),
        migrations.AddField(
            model_name='inappmessage',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inapp_messages', to='estateApp.company'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='estateApp.company'),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='support_participant_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
