# Generated by Django 5.2.8 on 2025-12-15 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0022_add_company_isolation_fields'),
        ('estateApp', '0095_estate_estate_size_unit_alter_estate_estate_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['company', 'email'], name='adminSuppor_company_444dcf_idx'),
        ),
    ]
