# Generated by Django 5.2.8 on 2026-01-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0002_configurationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['tier'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_admins',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_storage_gb',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='setup_fee',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_affiliates',
            field=models.IntegerField(blank=True, help_text='Maximum number of affiliates (null = unlimited)', null=True, verbose_name='Maximum Affiliates'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_allocations',
            field=models.IntegerField(blank=True, help_text='Maximum number of allocations (null = unlimited)', null=True, verbose_name='Maximum Allocations'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_clients',
            field=models.IntegerField(blank=True, help_text='Maximum number of clients (null = unlimited)', null=True, verbose_name='Maximum Clients'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_estates',
            field=models.IntegerField(blank=True, help_text='Maximum number of estates (null = unlimited)', null=True, verbose_name='Maximum Estates'),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_subscriptions', to='superAdmin.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional annual billing price with discount', max_digits=12, null=True, verbose_name='Annual Price (₦)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, help_text='Marketing description for this plan', verbose_name='Plan Description'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object of feature names and descriptions', verbose_name='Plan Features'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Can companies subscribe to this plan?', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_agents',
            field=models.IntegerField(default=1, help_text='Maximum number of team members', verbose_name='Maximum Agents'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_api_calls_daily',
            field=models.IntegerField(default=1000, help_text='Maximum API calls per 24 hours', verbose_name='Daily API Calls'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_plots',
            field=models.IntegerField(default=50, help_text='Maximum number of property listings', verbose_name='Maximum Plots'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira', max_digits=12, verbose_name='Monthly Price (₦)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='Subscription Tier'),
        ),
    ]
