# Generated by Django 5.1.4 on 2025-11-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0050_message_delete_for_everyone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_properties_owned', models.PositiveIntegerField(default=0, verbose_name='Total Properties Owned')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount Invested')),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Current Portfolio Value')),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ROI Percentage')),
                ('month_over_month_growth', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Month Over Month Growth (%)')),
                ('projected_value_1yr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Projected Value in 1 Year')),
                ('projected_value_5yr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Projected Value in 5 Years')),
                ('preferred_currency', models.CharField(default='NGN', max_length=3, verbose_name='Preferred Currency')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Notification Preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Client Dashboard',
                'verbose_name_plural': 'Client Dashboards',
            },
        ),
        migrations.CreateModel(
            name='ClientPropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='View Count')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='First Viewed At')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Last Viewed At')),
                ('is_interested', models.BooleanField(default=False, verbose_name='Is Interested')),
                ('is_favorited', models.BooleanField(default=False, verbose_name='Is Favorited')),
                ('client_notes', models.TextField(blank=True, null=True, verbose_name='Client Notes')),
            ],
            options={
                'verbose_name': 'Client Property View',
                'verbose_name_plural': 'Client Property Views',
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketerAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_tier', models.CharField(choices=[('bronze', 'Bronze - 2%'), ('silver', 'Silver - 3.5%'), ('gold', 'Gold - 5%'), ('platinum', 'Platinum - 7%+')], default='bronze', max_length=20, verbose_name='Commission Tier')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Commission Rate (%)')),
                ('properties_sold', models.PositiveIntegerField(default=0, verbose_name='Properties Sold')),
                ('total_commissions_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Commissions Earned')),
                ('total_commissions_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Commissions Paid')),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Sales Value')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('date_affiliated', models.DateTimeField(auto_now_add=True, verbose_name='Date Affiliated')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('suspension_date', models.DateTimeField(blank=True, null=True, verbose_name='Suspension Date')),
                ('termination_date', models.DateTimeField(blank=True, null=True, verbose_name='Termination Date')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name')),
            ],
            options={
                'verbose_name': 'Marketer Affiliation',
                'verbose_name_plural': 'Marketer Affiliations',
                'ordering': ['-date_affiliated'],
            },
        ),
        migrations.CreateModel(
            name='MarketerEarnedCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sale Amount')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission Rate (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference')),
                ('dispute_reason', models.TextField(blank=True, null=True, verbose_name='Dispute Reason')),
                ('disputed_at', models.DateTimeField(blank=True, null=True, verbose_name='Disputed At')),
            ],
            options={
                'verbose_name': 'Marketer Earned Commission',
                'verbose_name_plural': 'Marketer Earned Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Custom Domain'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_agents',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Agents Allowed'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_api_calls_daily',
            field=models.PositiveIntegerField(default=1000, verbose_name='Max API Calls Per Day'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_plots',
            field=models.PositiveIntegerField(default=50, verbose_name='Max Plots Allowed'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Ends At'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial - 14 Days'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20, verbose_name='Subscription Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter - 1 agent, 50 plots'), ('professional', 'Professional - 10 agents, 500 plots'), ('enterprise', 'Enterprise - Unlimited')], default='trial', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AddField(
            model_name='company',
            name='theme_color',
            field=models.CharField(default='#003366', max_length=7, verbose_name='Theme Color'),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial Ends At'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_status', 'subscription_ends_at'], name='estateApp_c_subscri_6b5075_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['api_key'], name='estateApp_c_api_key_ed8e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['custom_domain'], name='estateApp_c_custom__76dfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['stripe_customer_id'], name='estateApp_c_stripe__35f100_idx'),
        ),
        migrations.AddField(
            model_name='clientdashboard',
            name='client',
            field=models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='clientpropertyview',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='clientpropertyview',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_views', to='estateApp.estateplot', verbose_name='Plot'),
        ),
        migrations.AddField(
            model_name='marketeraffiliation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_affiliations', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketeraffiliation',
            name='marketer',
            field=models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_affiliations', to=settings.AUTH_USER_MODEL, verbose_name='Marketer'),
        ),
        migrations.AddField(
            model_name='marketerearnedcommission',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to='estateApp.marketeraffiliation', verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='marketerearnedcommission',
            name='plot_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_earned_commission', to='estateApp.plotallocation', verbose_name='Plot Allocation'),
        ),
        migrations.AlterUniqueTogether(
            name='clientpropertyview',
            unique_together={('client', 'plot')},
        ),
        migrations.AddIndex(
            model_name='marketeraffiliation',
            index=models.Index(fields=['marketer', 'status'], name='estateApp_m_markete_90fcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='marketeraffiliation',
            index=models.Index(fields=['company', 'status'], name='estateApp_m_company_1e9ffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketeraffiliation',
            unique_together={('marketer', 'company')},
        ),
        migrations.AddIndex(
            model_name='marketerearnedcommission',
            index=models.Index(fields=['affiliation', 'status'], name='estateApp_m_affilia_197a39_idx'),
        ),
        migrations.AddIndex(
            model_name='marketerearnedcommission',
            index=models.Index(fields=['status', 'paid_at'], name='estateApp_m_status_4c2865_idx'),
        ),
    ]
