# Generated by Django 5.2.8 on 2025-11-19 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0051_clientdashboard_clientpropertyview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Auto-generated: INV-YYYYMM-XXXXX', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Subscription fee + overage charges - credits', max_digits=12, verbose_name='Subscription & Usage Amount (₦)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Automatically calculated as 7.5% for Nigeria', max_digits=12, verbose_name='Tax Amount (7.5% VAT)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Invoice Status')),
                ('due_date', models.DateField(verbose_name='Payment Due Date')),
                ('issued_at', models.DateTimeField(blank=True, help_text='When status changed to "issued"', null=True, verbose_name='Date Issued')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was received', null=True, verbose_name='Date Paid')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this invoice', verbose_name='Invoice Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='estateApp.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount (₦)')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit', 'Credit Note'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(help_text='Transaction ID, check number, or reference for verification', max_length=100, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Payment Notes')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When payment was verified by admin', null=True, verbose_name='Verification Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='estateApp.invoice', verbose_name='Invoice')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='estateApp_i_company_faf9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'period_end'], name='estateApp_i_company_2e846a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='estateApp_i_status_4cde2f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_at'], name='estateApp_i_paid_at_2b802b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_method'], name='estateApp_p_invoice_c0ef20_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='estateApp_p_paid_at_0dc978_idx'),
        ),
    ]
