# Generated by Django 5.2.8 on 2025-11-19 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('estateApp', '0052_add_invoice_payment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_level',
            field=models.CharField(choices=[('system', 'System Administrator'), ('company', 'Company Administrator'), ('none', 'Not an Administrator')], default='none', help_text='Specify whether this is a system or company admin', max_length=20, verbose_name='Admin Level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='Check this to make user a system administrator who can access Tenant Admin dashboard', verbose_name='Is System Administrator'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('SUBSCRIPTION_CHANGE', 'Subscription Change'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_REVOKED', 'API Key Revoked'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_OPERATION', 'Bulk Operation'), ('SECURITY_EVENT', 'Security Event'), ('PAYMENT', 'Payment')], max_length=50)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='estateApp.company')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='estateApp_a_company_4bb21e_idx'), models.Index(fields=['user', '-created_at'], name='estateApp_a_user_id_99f422_idx'), models.Index(fields=['action', '-created_at'], name='estateApp_a_action_2890ec_idx')],
            },
        ),
    ]
