# Generated by Django 5.2.8 on 2025-11-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0053_customuser_admin_level_customuser_is_system_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='office_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Office Address'),
        ),
    ]
