# Generated by Django 5.2.8 on 2025-11-20 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0054_add_office_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='Subscription Tier')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, help_text='Marketing description for this plan', verbose_name='Plan Description')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira', max_digits=12, verbose_name='Monthly Price (₦)')),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional annual billing price with discount', max_digits=12, null=True, verbose_name='Annual Price (₦)')),
                ('max_plots', models.IntegerField(default=50, help_text='Maximum number of property listings', verbose_name='Maximum Plots')),
                ('max_agents', models.IntegerField(default=1, help_text='Maximum number of team members', verbose_name='Maximum Agents')),
                ('max_api_calls_daily', models.IntegerField(default=1000, help_text='Maximum API calls per 24 hours', verbose_name='Daily API Calls')),
                ('features', models.JSONField(blank=True, default=dict, help_text='JSON object of feature names and descriptions', verbose_name='Plan Features')),
                ('is_active', models.BooleanField(default=True, help_text='Can companies subscribe to this plan?', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['tier'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='api_calls_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API Calls Reset At'),
        ),
        migrations.AddField(
            model_name='company',
            name='api_calls_today',
            field=models.PositiveIntegerField(default=0, verbose_name='API Calls Today'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_agents_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Agents Count'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_plots_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Plots Count'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_renewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Last Renewed At'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Started At'),
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('subscription', 'Subscription Fee'), ('overage', 'Overage Charge'), ('refund', 'Refund'), ('credit', 'Credit Applied')], default='subscription', max_length=20, verbose_name='Charge Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Charge Amount (₦)')),
                ('description', models.TextField(blank=True, verbose_name='Charge Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Charge Status')),
                ('stripe_charge_id', models.CharField(blank=True, help_text='For tracking with Stripe', max_length=255, verbose_name='Stripe Charge ID')),
                ('billing_period_start', models.DateField(verbose_name='Billing Period Start')),
                ('billing_period_end', models.DateField(verbose_name='Billing Period End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='estateApp.company', verbose_name='Company')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice this charge is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='estateApp.invoice', verbose_name='Invoice')),
                ('subscription_plan', models.ForeignKey(blank=True, help_text='Plan this charge applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='estateApp.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='estateApp_b_company_1e8666_idx'), models.Index(fields=['company', 'created_at'], name='estateApp_b_company_f987e3_idx'), models.Index(fields=['status', 'processed_at'], name='estateApp_b_status_a7990c_idx'), models.Index(fields=['stripe_charge_id'], name='estateApp_b_stripe__0b5575_idx')],
            },
        ),
    ]
