# Generated by Django 5.2.8 on 2025-11-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0055_subscriptionplan_company_api_calls_reset_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('plots', 'Estate Plots'), ('agents', 'Agents/Marketers'), ('api_calls', 'API Calls'), ('storage', 'Storage'), ('exports', 'Exports'), ('reports', 'Reports')], max_length=20, verbose_name='Feature')),
                ('usage_count', models.BigIntegerField(default=0, verbose_name='Usage Count')),
                ('usage_limit', models.BigIntegerField(verbose_name='Usage Limit')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='Period')),
                ('reset_date', models.DateTimeField(verbose_name='Reset Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company Usage',
                'verbose_name_plural': 'Company Usage Metrics',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache/Redis'), ('api', 'API Server'), ('email', 'Email Service'), ('payment_gateway', 'Payment Gateway'), ('storage', 'Storage Service'), ('websocket', 'WebSocket')], max_length=50, verbose_name='Service Name')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Status')),
                ('response_time_ms', models.FloatField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='Last Check')),
                ('last_failure', models.DateTimeField(blank=True, null=True, verbose_name='Last Failure')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alert Sent')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alert Sent At')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-last_check'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('trial_ending', 'Trial Ending'), ('trial_expired', 'Trial Expired'), ('grace_period', 'Grace Period Active'), ('subscription_renewing', 'Subscription Renewing'), ('subscription_failed', 'Subscription Payment Failed'), ('usage_warning', 'Usage Limit Warning'), ('usage_exceeded', 'Usage Limit Exceeded'), ('read_only_mode', 'Read-Only Mode Activated'), ('data_deletion_warning', 'Data Deletion Warning'), ('system_alert', 'System Alert')], max_length=30, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='warning', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='Action URL')),
                ('action_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action Label')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Is Dismissible')),
                ('show_on_dashboard', models.BooleanField(default=True, verbose_name='Show on Dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dismissed At')),
            ],
            options={
                'verbose_name': 'Subscription Alert',
                'verbose_name_plural': 'Subscription Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='Tier')),
                ('name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Price')),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Price')),
                ('max_plots', models.PositiveIntegerField(verbose_name='Max Plots')),
                ('max_agents', models.PositiveIntegerField(verbose_name='Max Agents')),
                ('max_api_calls_daily', models.PositiveIntegerField(verbose_name='Max Daily API Calls')),
                ('max_storage_gb', models.PositiveIntegerField(verbose_name='Max Storage GB')),
                ('features', models.JSONField(default=list, verbose_name='Available Features')),
                ('support_level', models.CharField(choices=[('email', 'Email Support'), ('priority', 'Priority Support'), ('dedicated', 'Dedicated Support')], default='email', max_length=20, verbose_name='Support Level')),
                ('sla_uptime_percent', models.DecimalField(decimal_places=2, default=99.5, max_digits=5, verbose_name='SLA Uptime %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('performance', 'Performance Issue'), ('security', 'Security Issue'), ('maintenance', 'Maintenance'), ('downtime', 'Downtime'), ('capacity', 'Capacity Issue'), ('error', 'Error')], max_length=20, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='warning', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('resolution_steps', models.TextField(blank=True, null=True, verbose_name='Resolution Steps')),
                ('affected_users_count', models.PositiveIntegerField(default=0, verbose_name='Affected Users Count')),
                ('affected_companies_count', models.PositiveIntegerField(default=0, verbose_name='Affected Companies Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='data_deletion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Deletion Date'),
        ),
        migrations.AddField(
            model_name='company',
            name='features_available',
            field=models.JSONField(blank=True, default=list, verbose_name='Available Features'),
        ),
        migrations.AddField(
            model_name='company',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grace Period Ends At'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_read_only_mode',
            field=models.BooleanField(default=False, verbose_name='Read-Only Mode'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_status', 'is_read_only_mode'], name='estateApp_c_subscri_d4f4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['trial_ends_at', 'grace_period_ends_at'], name='estateApp_c_trial_e_c7af69_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['data_deletion_date'], name='estateApp_c_data_de_32d312_idx'),
        ),
        migrations.AddField(
            model_name='companyusage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='estateApp.company'),
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together={('service_name',)},
        ),
        migrations.AddField(
            model_name='subscriptionalert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_alerts', to='estateApp.company'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['severity', 'status'], name='estateApp_s_severit_a083ac_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['alert_type'], name='estateApp_s_alert_t_40f5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='companyusage',
            index=models.Index(fields=['company', 'feature'], name='estateApp_c_company_077341_idx'),
        ),
        migrations.AddIndex(
            model_name='companyusage',
            index=models.Index(fields=['reset_date'], name='estateApp_c_reset_d_c8e1f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyusage',
            unique_together={('company', 'feature', 'period')},
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['company', 'status'], name='estateApp_s_company_90b052_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['severity', 'created_at'], name='estateApp_s_severit_126705_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['alert_type'], name='estateApp_s_alert_t_349f28_idx'),
        ),
    ]
