# Generated by Django 5.2.8 on 2025-11-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0056_companyusage_healthcheck_subscriptionalert_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plotallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estatefloorplan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_floor_plans', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estatelayout',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_layouts', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estatemap',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_maps', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estateplot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_plots', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estateprototype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_prototypes', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='message',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='plotallocation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_allocations', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='plotnumber',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_numbers', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='plotsize',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_sizes', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='plotsizeunits',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_size_units', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='progressstatus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_statuses', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_requests', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='plotnumber',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Plot Number'),
        ),
        migrations.AlterField(
            model_name='plotsize',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Plot Size'),
        ),
        migrations.AlterUniqueTogether(
            name='plotallocation',
            unique_together={('company', 'estate', 'plot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='plotnumber',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='plotsize',
            unique_together={('company', 'size')},
        ),
    ]
