# Generated by Django 5.2.8 on 2025-11-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0057_alter_plotallocation_unique_together_estate_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketercommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commissions', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketerperformancerecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_performance_records', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketertarget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_targets', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='promotionaloffer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_offers', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='propertyprice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='estateApp.company', verbose_name='Company'),
        ),
    ]
