# Generated by Django 5.2.8 on 2025-11-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0058_marketercommission_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_dashboards', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='clientpropertyview',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_property_views', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='estateamenitie',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_amenities', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketerearnedcommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_earned_commissions', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='notificationdispatch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device_tokens', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='estateApp.company', verbose_name='Company'),
        ),
    ]
