# Generated by Django 5.2.8 on 2025-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0059_clientdashboard_company_clientpropertyview_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotallocation',
            name='client_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email used to link properties across companies for cross-company portfolio tracking', max_length=255, null=True, verbose_name='Client Email'),
        ),
    ]
