# Generated by Django 5.1.2 on 2025-11-20 22:05

from django.db import migrations


def populate_client_emails(apps, schema_editor):
    """
    Populate client_email field on existing PlotAllocation records
    Uses the email from the related ClientUser
    """
    PlotAllocation = apps.get_model('estateApp', 'PlotAllocation')
    
    updated_count = 0
    for allocation in PlotAllocation.objects.select_related('client').iterator():
        if allocation.client and allocation.client.email and not allocation.client_email:
            allocation.client_email = allocation.client.email
            allocation.save(update_fields=['client_email'])
            updated_count += 1
    
    print(f"✅ Populated client_email for {updated_count} PlotAllocation records")


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear client_email field"""
    PlotAllocation = apps.get_model('estateApp', 'PlotAllocation')
    PlotAllocation.objects.all().update(client_email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0060_add_client_email_to_plotallocation'),
    ]

    operations = [
        migrations.RunPython(populate_client_emails, reverse_populate),
    ]
