# Generated by Django 5.2.8 on 2025-11-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0061_populate_client_email_on_plotallocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for personalized URLs', max_length=100, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
