# Generated by Django 5.2.8 on 2025-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0062_add_user_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['company', 'sender', 'recipient'], name='estateApp_m_company_76e12d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['company', 'is_read'], name='estateApp_m_company_59d682_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read', 'company'], name='estateApp_m_recipie_73ba37_idx'),
        ),
    ]
