# Generated by Django 5.2.8 on 2025-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0063_add_message_security_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cac_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CAC Registration Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cashier Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='cashier_signature',
            field=models.ImageField(blank=True, null=True, upload_to='cashier_signatures/', verbose_name='Cashier Signature'),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Receipt Counter'),
        ),
    ]
