# Generated by Django 5.2.8 on 2025-11-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0064_company_cac_number_company_cashier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cac_number',
        ),
    ]
