# Generated by Django 5.2.8 on 2025-11-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0065_remove_cac_number_use_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'company_profile', 'role')},
        ),
    ]
