# Generated by Django 5.2.8 on 2025-11-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0066_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='company_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID for this client within their company (e.g., CLT-ABC-001)', max_length=50, null=True, verbose_name='Company Client ID'),
        ),
        migrations.AddField(
            model_name='marketeruser',
            name='company_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID for this marketer within their company (e.g., MKT-ABC-001)', max_length=50, null=True, verbose_name='Company Marketer ID'),
        ),
    ]
