# Generated by Django 5.2.8 on 2025-11-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0068_add_tenant_admin_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdashboard',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientdashboard',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='clientpropertyview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientpropertyview',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpropertyview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientpropertyview',
            name='plot',
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
        migrations.AlterUniqueTogether(
            name='marketeraffiliation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marketeraffiliation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketeraffiliation',
            name='marketer',
        ),
        migrations.RemoveField(
            model_name='marketerearnedcommission',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='marketerearnedcommission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketerearnedcommission',
            name='plot_allocation',
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='billingrecord',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Billing Record', 'verbose_name_plural': 'Billing Records'},
        ),
        migrations.AlterModelOptions(
            name='companyusage',
            options={'ordering': ['-date'], 'verbose_name': 'Company Usage', 'verbose_name_plural': 'Company Usage Records'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionalert',
            options={'ordering': ['-alert_date'], 'verbose_name': 'Subscription Alert', 'verbose_name_plural': 'Subscription Alerts'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['monthly_price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='estateApp_a_company_4bb21e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='estateApp_a_user_id_99f422_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='estateApp_a_action_2890ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='estateApp_b_company_1e8666_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='estateApp_b_company_f987e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='estateApp_b_status_a7990c_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='estateApp_b_stripe__0b5575_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_subscri_6b5075_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_subscri_d4f4b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_trial_e_c7af69_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyusage',
            name='estateApp_c_company_077341_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyusage',
            name='estateApp_c_reset_d_c8e1f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='estateApp_i_company_faf9fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='estateApp_i_company_2e846a_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='estateApp_i_status_4cde2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='estateApp_i_paid_at_2b802b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_76e12d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_59d682_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_recipie_73ba37_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='estateApp_p_invoice_c0ef20_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='estateApp_p_paid_at_0dc978_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionalert',
            name='estateApp_s_company_90b052_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionalert',
            name='estateApp_s_severit_126705_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionalert',
            name='estateApp_s_alert_t_349f28_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemalert',
            name='estateApp_s_severit_a083ac_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plotallocation',
            unique_together={('estate', 'plot_number')},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_repr',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_values',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_path',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='invoice',
        ),
        migrations.AlterUniqueTogether(
            name='companyusage',
            unique_together={('company', 'date')},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='plotsizeunits',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='action_label',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='dismissed_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='is_dismissible',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='show_on_dashboard',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='title',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='affected_companies_count',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='affected_users_count',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='resolution_steps',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='status',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import')], default='create', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(default='unknown', help_text='Model name or resource type', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyusage',
            name='agents_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyusage',
            name='api_calls_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyusage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyusage',
            name='plots_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='completed', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionalert',
            name='alert_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionalert',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionalert',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='source',
            field=models.CharField(default='system', help_text='Source system or component', max_length=100),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional context data'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='charge_type',
            field=models.CharField(choices=[('subscription', 'Subscription Fee'), ('overage', 'Overage Charge'), ('one_time', 'One-time Charge'), ('refund', 'Refund')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateApp.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='company_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company User ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_calls_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API Calls Reset Time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_calls_today',
            field=models.IntegerField(default=0, verbose_name='API Calls Today'),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_agents_count',
            field=models.IntegerField(default=0, verbose_name='Current Agents Count'),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_plots_count',
            field=models.IntegerField(default=0, verbose_name='Current Plots Count'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Domain'),
        ),
        migrations.AlterField(
            model_name='company',
            name='data_deletion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Deletion Date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='features_available',
            field=models.JSONField(blank=True, default=dict, verbose_name='Available Features'),
        ),
        migrations.AlterField(
            model_name='company',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grace Period Ends'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_agents',
            field=models.IntegerField(default=1, verbose_name='Max Agents Allowed'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_api_calls_daily',
            field=models.IntegerField(default=1000, verbose_name='Max API Calls Per Day'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_plots',
            field=models.IntegerField(default=50, verbose_name='Max Plots Allowed'),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_address',
            field=models.TextField(blank=True, null=True, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='receipt_counter',
            field=models.IntegerField(default=0, verbose_name='Receipt Counter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Ends'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_renewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Renewed'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Started'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20, verbose_name='Subscription Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AlterField(
            model_name='company',
            name='theme_color',
            field=models.CharField(default='#667eea', max_length=7, verbose_name='Theme Color'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial Ends'),
        ),
        migrations.AlterField(
            model_name='companyusage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='companyusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketeruser',
            name='company_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company User ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='estateApp.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plotallocation',
            name='client_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Client Email'),
        ),
        migrations.AlterField(
            model_name='subscriptionalert',
            name='alert_type',
            field=models.CharField(choices=[('trial_ending', 'Trial Ending Soon'), ('subscription_ending', 'Subscription Ending Soon'), ('payment_failed', 'Payment Failed'), ('usage_limit', 'Usage Limit Reached')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict, help_text='JSON object of available features'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_agents',
            field=models.IntegerField(help_text='Maximum number of agents allowed'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_api_calls_daily',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_plots',
            field=models.IntegerField(help_text='Maximum number of plots allowed'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='alert_type',
            field=models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('billing', 'Billing'), ('performance', 'Performance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', '-timestamp'], name='estateApp_a_company_9eb127_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='estateApp_a_user_id_14737c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='estateApp_a_action__8b79cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource'], name='estateApp_a_resourc_c916be_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['company', '-processed_at'], name='estateApp_b_company_704ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['status'], name='estateApp_b_status_87d6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_tier', 'subscription_status'], name='estateApp_c_subscri_0f1201_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_ends_at'], name='estateApp_c_subscri_0f17b9_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['trial_ends_at'], name='estateApp_c_trial_e_b84008_idx'),
        ),
        migrations.AddIndex(
            model_name='companyusage',
            index=models.Index(fields=['company', '-date'], name='estateApp_c_company_b61cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', '-invoice_date'], name='estateApp_i_company_e503f9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='estateApp_i_status_94ac40_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['company', '-alert_date'], name='estateApp_s_company_5ca8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['is_sent'], name='estateApp_s_is_sent_490a52_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['is_active', '-created_at'], name='estateApp_s_is_acti_a40eba_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['severity'], name='estateApp_s_severit_a95fae_idx'),
        ),
        migrations.DeleteModel(
            name='ClientDashboard',
        ),
        migrations.DeleteModel(
            name='ClientPropertyView',
        ),
        migrations.DeleteModel(
            name='MarketerAffiliation',
        ),
        migrations.DeleteModel(
            name='MarketerEarnedCommission',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='period',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='reset_date',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='usage_limit',
        ),
    ]
