# Generated by Django 5.2.8 on 2025-11-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0074_fix_userdevicetoken_constraint'),
    ]

    operations = [
        # IsolationAuditLog creation moved to a dedicated migration (0077_create_isolation_auditlog)
        # to avoid duplicate model creation and keep concerns separated.
        migrations.RemoveField(
            model_name='billinghistory',
            name='subscription',
        ),
        # Removed explicit field removals for BillingRecord (company, invoice, subscription_plan)
        # because the BillingRecord model is deleted later in this migration. Keeping
        # the DeleteModel operation is sufficient and prevents failures when fields
        # are already absent in historical states during test DB creation.
        migrations.AlterUniqueTogether(
            name='companyusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='company',
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscriptionbillingmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscriptionbillingmodel',
            name='current_plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
        migrations.DeleteModel(
            name='SystemAlert',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_subscri_d4f4b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_trial_e_c7af69_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_data_de_32d312_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_76e12d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_59d682_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_recipie_73ba37_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientdashboard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientpropertyview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='estateamenitie',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatefloorplan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatelayout',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatemap',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estateplot',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estateprototype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketercommission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketerearnedcommission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketerperformancerecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketertarget',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketeruser',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notificationdispatch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='plotallocation',
            unique_together={('estate', 'plot_number')},
        ),
        migrations.RemoveField(
            model_name='plotsizeunits',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='progressstatus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='promotionaloffer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='propertyrequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userdevicetoken',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='company',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('SUBSCRIPTION_CHANGE', 'Subscription Change'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_REVOKED', 'API Key Revoked'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_OPERATION', 'Bulk Operation'), ('SECURITY_EVENT', 'Security Event'), ('PAYMENT', 'Payment')], default='READ', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_address',
            field=models.TextField(blank=True, null=True, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='receipt_counter',
            field=models.PositiveIntegerField(default=1, verbose_name='Receipt Counter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_level',
            field=models.CharField(choices=[('system', 'System Administrator'), ('company', 'Company Administrator'), ('none', 'No Admin Access')], default='none', help_text='Defines the administrative access level: system (platform-wide), company (single company), or none', max_length=20, verbose_name='Admin Level'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='System admins can manage the entire platform across all companies', verbose_name='Is System Administrator'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this estate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period End Date'),
        ),

        migrations.DeleteModel(
            name='BillingHistory',
        ),
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.DeleteModel(
            name='CompanyUsage',
        ),
        migrations.DeleteModel(
            name='SubscriptionAlert',
        ),
        migrations.DeleteModel(
            name='SubscriptionBillingModel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='plotallocation',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='plotallocation',
            name='company',
        ),

    ]
