# Generated by Django 5.2.8 on 2025-11-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0074_fix_userdevicetoken_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('READ', 'Record Accessed'), ('UPDATE', 'Record Modified'), ('DELETE', 'Record Deleted'), ('ACCESS_DENIED', 'Access Denied'), ('PERMISSION_ERROR', 'Permission Error')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='subscription_plan',
        ),
        migrations.AlterUniqueTogether(
            name='companyusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyusage',
            name='company',
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscriptionbillingmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscriptionbillingmodel',
            name='current_plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
        migrations.DeleteModel(
            name='SystemAlert',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_subscri_d4f4b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_trial_e_c7af69_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='estateApp_c_data_de_32d312_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_76e12d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_company_59d682_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='estateApp_m_recipie_73ba37_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientdashboard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientpropertyview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='estateamenitie',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatefloorplan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatelayout',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estatemap',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estateplot',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estateprototype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketercommission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketerearnedcommission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketerperformancerecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketertarget',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketeruser',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notificationdispatch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='plotallocation',
            unique_together={('estate', 'plot_number')},
        ),
        migrations.RemoveField(
            model_name='plotsizeunits',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='progressstatus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='promotionaloffer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='propertyrequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userdevicetoken',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='company',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('SUBSCRIPTION_CHANGE', 'Subscription Change'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_REVOKED', 'API Key Revoked'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_OPERATION', 'Bulk Operation'), ('SECURITY_EVENT', 'Security Event'), ('PAYMENT', 'Payment')], default='READ', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_address',
            field=models.TextField(blank=True, null=True, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='receipt_counter',
            field=models.PositiveIntegerField(default=1, verbose_name='Receipt Counter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_level',
            field=models.CharField(choices=[('system', 'System Administrator'), ('company', 'Company Administrator'), ('none', 'No Admin Access')], default='none', help_text='Defines the administrative access level: system (platform-wide), company (single company), or none', max_length=20, verbose_name='Admin Level'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='System admins can manage the entire platform across all companies', verbose_name='Is System Administrator'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this estate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period End Date'),
        ),
        migrations.AddField(
            model_name='isolationauditlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_audit_logs', to='estateApp.company'),
        ),
        migrations.AddField(
            model_name='isolationauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BillingHistory',
        ),
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.DeleteModel(
            name='CompanyUsage',
        ),
        migrations.DeleteModel(
            name='SubscriptionAlert',
        ),
        migrations.DeleteModel(
            name='SubscriptionBillingModel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='plotallocation',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='plotallocation',
            name='company',
        ),
        migrations.AddIndex(
            model_name='isolationauditlog',
            index=models.Index(fields=['company', 'timestamp'], name='estateApp_i_company_5b9cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='isolationauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='estateApp_i_user_id_580353_idx'),
        ),
    ]
