# Generated by Django 5.2.8 on 2025-11-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0075_isolationauditlog_remove_billinghistory_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='CEO Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary CEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceos', to='estateApp.company')),
            ],
            options={
                'verbose_name': 'Company CEO',
                'verbose_name_plural': 'Company CEOs',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
