# Generated by Django 5.2.8 on 2025-11-24 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0077_create_isolation_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='isolationauditlog',
            name='estateApp_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='isolationauditlog',
            new_name='estateApp_i_company_5b9cdc_idx',
            old_name='estateApp_company_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='isolationauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Record Created'), ('READ', 'Record Accessed'), ('UPDATE', 'Record Modified'), ('DELETE', 'Record Deleted'), ('ACCESS_DENIED', 'Access Denied'), ('PERMISSION_ERROR', 'Permission Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='isolationauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolation_audit_logs', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='isolationauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='isolationauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='isolationauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='estateApp_i_user_id_580353_idx'),
        ),
    ]
