# Generated by Django 5.2.8 on 2025-11-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0081_alter_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMarketerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_assignments', to='estateApp.clientuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_marketer_assignments', to='estateApp.company')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='estateApp.marketeruser')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'company'], name='estateApp_c_client__97fc10_idx')],
                'unique_together': {('client', 'marketer', 'company')},
            },
        ),
    ]
