# Generated by Django 5.2.8 on 2025-11-28 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0082_clientmarketerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='company_client_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Company Client ID'),
        ),
        migrations.AddField(
            model_name='marketeruser',
            name='company_marketer_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Company Marketer ID'),
        ),
        # note: `message.company` column already existed in the DB schema; skip adding it here
    ]
