# Generated by Django 5.2.8 on 2025-11-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0083_clientuser_company_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='company_client_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Company Client UID'),
        ),
        migrations.AddField(
            model_name='marketeruser',
            name='company_marketer_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Company Marketer UID'),
        ),
        # Note: `message.company` already exists in the DB schema; skip adding it here.
    ]
