# Generated by Django 5.2.8 on 2025-11-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0084_clientuser_company_client_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Sequence key, e.g. 'client' or 'marketer'", max_length=50)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='estateApp.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key'], name='estateApp_c_company_f6608f_idx')],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
