# Generated by Django 5.2.8 on 2025-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0086_company_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='Is Encrypted'),
        ),
    ]
