# Generated by Django 5.2.8 on 2025-12-03 18:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0089_add_company_to_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('sla_status', models.CharField(choices=[('compliant', 'Compliant'), ('at_risk', 'At Risk'), ('breached', 'Breached'), ('resolved', 'Resolved')], default='compliant', max_length=20, verbose_name='SLA Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='First Response At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='Response Time')),
                ('resolution_time', models.DurationField(blank=True, null=True, verbose_name='Resolution Time')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent')),
                ('escalation_level', models.PositiveIntegerField(default=0, verbose_name='Escalation Level')),
            ],
            options={
                'verbose_name': 'Chat Assignment',
                'verbose_name_plural': 'Chat Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Unread Count')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Last Message At')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified At')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dismissed At')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Chat Queue',
                'verbose_name_plural': 'Chat Queues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatResponseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('total_chats', models.PositiveIntegerField(default=0, verbose_name='Total Chats')),
                ('responded_chats', models.PositiveIntegerField(default=0, verbose_name='Responded Chats')),
                ('average_response_time', models.DurationField(blank=True, null=True, verbose_name='Average Response Time')),
                ('sla_compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='SLA Compliance Rate (%)')),
                ('breached_chats', models.PositiveIntegerField(default=0, verbose_name='Breached Chats')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, verbose_name='Priority')),
                ('response_time_hours', models.PositiveIntegerField(verbose_name='Response Time (Hours)')),
                ('resolution_time_hours', models.PositiveIntegerField(verbose_name='Resolution Time (Hours)')),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Working Hours Start')),
                ('working_hours_end', models.TimeField(default=datetime.time(17, 0), verbose_name='Working Hours End')),
                ('include_weekends', models.BooleanField(default=False, verbose_name='Include Weekends')),
            ],
        ),
        migrations.AlterModelOptions(
            name='marketerperformancerecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='companyclientprofile',
            name='unique_client_company',
        ),
        migrations.RemoveConstraint(
            model_name='companymarketerprofile',
            name='unique_marketer_company',
        ),
        migrations.RenameIndex(
            model_name='companyclientprofile',
            new_name='estateApp_c_company_2605fe_idx',
            old_name='estateApp_c_company_56fg7h_idx',
        ),
        migrations.RenameIndex(
            model_name='companyclientprofile',
            new_name='estateApp_c_client__be0ed5_idx',
            old_name='estateApp_c_client_89ij1k_idx',
        ),
        migrations.RenameIndex(
            model_name='companymarketerprofile',
            new_name='estateApp_c_company_b1024a_idx',
            old_name='estateApp_c_company_12ab3d_idx',
        ),
        migrations.RenameIndex(
            model_name='companymarketerprofile',
            new_name='estateApp_c_markete_80aae6_idx',
            old_name='estateApp_c_markete_4cdef5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketerperformancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marketertarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commissions', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketerperformancerecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_performance_records', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='marketertarget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_targets', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='plotnumber',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this plot number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_numbers', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='plotsize',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this plot size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_sizes', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='estateApp.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='estateApp.company'),
        ),
        migrations.AlterUniqueTogether(
            name='companyclientprofile',
            unique_together={('client', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companymarketerprofile',
            unique_together={('marketer', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='marketercommission',
            unique_together={('company', 'marketer')},
        ),
        migrations.AlterUniqueTogether(
            name='marketerperformancerecord',
            unique_together={('company', 'marketer', 'period_type', 'specific_period')},
        ),
        migrations.AlterUniqueTogether(
            name='marketertarget',
            unique_together={('company', 'period_type', 'specific_period', 'marketer')},
        ),
        migrations.AddIndex(
            model_name='marketerperformancerecord',
            index=models.Index(fields=['company', 'marketer'], name='estateApp_m_company_62006c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketerperformancerecord',
            index=models.Index(fields=['company', 'period_type'], name='estateApp_m_company_e1639c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketerperformancerecord',
            index=models.Index(fields=['company', 'specific_period'], name='estateApp_m_company_18aa64_idx'),
        ),
        migrations.AddIndex(
            model_name='marketerperformancerecord',
            index=models.Index(fields=['company', 'created_at'], name='estateApp_m_company_a9a789_idx'),
        ),
        migrations.AddIndex(
            model_name='marketertarget',
            index=models.Index(fields=['company', 'period_type'], name='estateApp_m_company_be33f7_idx'),
        ),
        migrations.AddIndex(
            model_name='marketertarget',
            index=models.Index(fields=['company', 'specific_period'], name='estateApp_m_company_03dd16_idx'),
        ),
        migrations.AddField(
            model_name='chatassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='chatassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_assignments', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='last_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for', to='estateApp.message', verbose_name='Last Message'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_queues', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_queues', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='first_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='estateApp.message', verbose_name='First Message'),
        ),
        migrations.AddField(
            model_name='chatassignment',
            name='chat_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='estateApp.chatqueue', verbose_name='Chat Queue'),
        ),
        migrations.AddField(
            model_name='chatresponsetracking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_tracking', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='chatsla',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_slas', to='estateApp.company', verbose_name='Company'),
        ),
        migrations.AlterUniqueTogether(
            name='chatnotification',
            unique_together={('recipient', 'company', 'client')},
        ),
        migrations.AddIndex(
            model_name='chatqueue',
            index=models.Index(fields=['status', 'priority'], name='estateApp_c_status_ae5727_idx'),
        ),
        migrations.AddIndex(
            model_name='chatqueue',
            index=models.Index(fields=['company', 'status'], name='estateApp_c_company_ccee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatqueue',
            index=models.Index(fields=['client', 'company'], name='estateApp_c_client__f96082_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatqueue',
            unique_together={('client', 'company')},
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['chat_queue', 'assigned_to'], name='estateApp_c_chat_qu_043463_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['status', 'assigned_at'], name='estateApp_c_status_2dbe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['sla_status', 'response_time'], name='estateApp_c_sla_sta_1bb799_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatassignment',
            unique_together={('chat_queue', 'assigned_to')},
        ),
        migrations.AlterUniqueTogether(
            name='chatresponsetracking',
            unique_together={('company', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='chatsla',
            unique_together={('company', 'priority')},
        ),
    ]
