# Generated by Django 5.2.8 on 2025-12-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0090_chatassignment_chatnotification_chatqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_full_control',
            field=models.BooleanField(default=False, help_text='When enabled, this admin can access company profile without master admin password verification', verbose_name='Has Full Control'),
        ),
    ]
