# Generated by Django 5.2.8 on 2025-12-07 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0091_add_has_full_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this notification belongs to. Null means global/system notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='estateApp.company'),
        ),
        migrations.CreateModel(
            name='SubscriptionBillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'TRIAL'), ('active', 'ACTIVE'), ('grace', 'GRACE_PERIOD'), ('suspended', 'SUSPENDED'), ('cancelled', 'CANCELLED'), ('expired', 'EXPIRED')], default='trial', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('grace_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('free_trial', 'Free Trial')], max_length=20, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('annual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('warning_level', models.IntegerField(default=0, help_text='0=No warning, 1=Yellow, 2=Orange, 3=Red')),
                ('last_warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='estateApp.company')),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='estateApp.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Billing',
                'verbose_name_plural': 'Subscription Billings',
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('proration', 'Proration'), ('adjustment', 'Adjustment')], max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.TextField()),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('billing_date', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='estateApp.subscriptionbillingmodel')),
            ],
            options={
                'verbose_name': 'Billing History',
                'verbose_name_plural': 'Billing Histories',
                'ordering': ['-billing_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('daily_limit', models.IntegerField(blank=True, null=True)),
                ('monthly_limit', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='estateApp.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Feature Access',
                'verbose_name_plural': 'Subscription Feature Access',
                'unique_together': {('plan', 'feature_name')},
            },
        ),
    ]
