# Generated by Django 5.2.8 on 2025-12-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0092_add_company_to_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketeraffiliation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
