# Generated by Django 5.2.8 on 2025-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0093_update_marketer_affiliation_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Select Title'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Engr', 'Engr'), ('Barr', 'Barr'), ('Chief', 'Chief'), ('Hon', 'Hon'), ('Alhaji', 'Alhaji'), ('Alhaja', 'Alhaja'), ('Pastor', 'Pastor'), ('Rev', 'Rev'), ('Bishop', 'Bishop'), ('Imam', 'Imam'), ('Sir', 'Sir'), ('Dame', 'Dame'), ('Prince', 'Prince'), ('Princess', 'Princess'), ('Otunba', 'Otunba'), ('Oloye', 'Oloye'), ('High Chief', 'High Chief')], max_length=20, null=True, verbose_name='Title'),
        ),
    ]
