# Generated by Django 5.2.8 on 2025-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0094_add_title_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='estate_size_unit',
            field=models.CharField(choices=[('Square Meters', 'Square Meters (m²)'), ('Square Feet', 'Square Feet (sq ft)'), ('Hectares', 'Hectares (ha)'), ('Acres', 'Acres'), ('Square Kilometers', 'Square Kilometers (km²)')], default='Hectares', max_length=50, verbose_name='Estate Size Unit'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estate Size'),
        ),
    ]
