# Generated by Django 5.2.8 on 2025-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0097_drop_bad_companyusage_unique_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyusage',
            new_name='estateApp_c_company_077341_idx',
            old_name='estateApp_c_company_096_restore_idx',
        ),
        migrations.RenameIndex(
            model_name='companyusage',
            new_name='estateApp_c_reset_d_c8e1f6_idx',
            old_name='estateApp_c_reset_d_096_restore_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionalert',
            new_name='estateApp_s_company_90b052_idx',
            old_name='estateApp_s_company_096_restore_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionalert',
            new_name='estateApp_s_severit_126705_idx',
            old_name='estateApp_s_severit_096_restore_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionalert',
            new_name='estateApp_s_alert_t_349f28_idx',
            old_name='estateApp_s_alert_t_096_restore_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='estateApp_s_severit_a083ac_idx',
            old_name='estateApp_s_severit_096_sys_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='estateApp_s_alert_t_40f5f4_idx',
            old_name='estateApp_s_alert_t_096_sys_idx',
        ),
        migrations.AddField(
            model_name='subscriptionbillingmodel',
            name='billing_contact',
            field=models.CharField(blank=True, help_text='Billing contact name or department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionbillingmodel',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email for receipts and renewal notices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial - 14 Days'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20, verbose_name='Subscription Status'),
        ),
    ]
