# Generated by Django 5.2.8 on 2026-01-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0002_add_paystack_customer_code'),
        ('estateApp', '0098_add_billing_email_contact'),
    ]

    operations = [
    ]
