# Generated by Django 5.2.8 on 2026-01-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0099_merge_20260113_0857'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='estateApp_c_paystac_849afd_idx',
            old_name='estateapp_c_paysta_idx',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_affiliates',
            field=models.IntegerField(blank=True, help_text='Maximum number of affiliates (null = unlimited)', null=True, verbose_name='Maximum Affiliates'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_allocations',
            field=models.IntegerField(blank=True, help_text='Maximum number of allocations (null = unlimited)', null=True, verbose_name='Maximum Allocations'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_clients',
            field=models.IntegerField(blank=True, help_text='Maximum number of clients (null = unlimited)', null=True, verbose_name='Maximum Clients'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_estates',
            field=models.IntegerField(blank=True, help_text='Maximum number of estates (null = unlimited)', null=True, verbose_name='Maximum Estates'),
        ),
    ]
