# Generated by Django 5.2.8 on 2026-01-13 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0100_rename_estateapp_c_paysta_idx_estateapp_c_paystac_849afd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promotional code (e.g., WELCOME20, NEWYEAR25)', max_length=50, unique=True, verbose_name='Promo Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20 for 20%) or Fixed amount in Naira', max_digits=10, verbose_name='Discount Value')),
                ('description', models.TextField(blank=True, help_text='Internal description for this promo code', verbose_name='Description')),
                ('valid_from', models.DateField(blank=True, help_text='Start date for promo code validity', null=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, help_text='End date for promo code validity', null=True, verbose_name='Valid Until')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum total uses (null = unlimited)', null=True, verbose_name='Maximum Uses')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this code has been used', verbose_name='Used Count')),
                ('max_uses_per_user', models.IntegerField(default=1, help_text='Maximum uses per user', verbose_name='Max Uses Per User')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum subscription amount required', max_digits=12, null=True, verbose_name='Minimum Amount (₦)')),
                ('applicable_plans', models.JSONField(blank=True, default=list, help_text='List of plan tiers this code applies to (empty = all plans)', verbose_name='Applicable Plans')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promo code is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
