# Generated by Django 5.2.8 on 2026-01-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0101_promocode'),
        ('superAdmin', '0003_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbillingmodel',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_subscriptions', to='superAdmin.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionfeatureaccess',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='superAdmin.subscriptionplan'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
